# Generated by Django 5.1.6 on 2026-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_delay_minutes_trip_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
