# Generated by Django 5.1.6 on 2026-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_parcel_pricing_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='companies/documents/'),
        ),
        migrations.AddField(
            model_name='companynotificationsettings',
            name='sms_claim_response',
            field=models.BooleanField(default=True),
        ),
    ]
