# Generated by Django 5.1.6 on 2026-07-21 12:02
#
# Impact sur les donnees existantes : aucun.
# - `info_request_message` est une TextField(blank=True) : les lignes existantes
#   recoivent la chaine vide (pas de valeur NULL, pas de backfill necessaire).
# - `status` n'ajoute qu'un choix (`info_requested`) : aucune valeur existante
#   n'est modifiee, la contrainte reste un simple varchar(20).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='info_request_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('info_requested', 'Informations complementaires demandees'), ('active', 'Active'), ('suspended', 'Suspendue'), ('rejected', 'Rejetee')], default='pending', max_length=20),
        ),
    ]
