# Generated by Django 5.1.6 on 2026-08-29 20:33

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_info_request_message_alter_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='baggage_policy',
            field=models.JSONField(default=apps.companies.models.default_baggage_policy),
        ),
    ]
