# Generated by Django 5.1.6 on 2026-06-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_parcel_pricing_config'),
        ('geography', '0002_city_station_options'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_phone', models.CharField(max_length=30)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tariff', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('qr_code', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registered', 'Enregistre'), ('in_transit', 'En transit'), ('arrived', 'Arrive'), ('notified', 'Destinataire prevenu'), ('collected', 'Remis')], default='registered', max_length=20)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='companies.company')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_received', to='geography.city')),
                ('destination_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels_destination', to='geography.station')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_sent', to='geography.city')),
                ('origin_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels_origin', to='geography.station')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_parcels', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('sms', 'SMS'), ('call', 'Appel manuel')], default='sms', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='parcels.parcel')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcel_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification colis',
                'verbose_name_plural': 'Notifications colis',
                'ordering': ['-created_at'],
            },
        ),
    ]
