# Generated by Django 5.1.6 on 2026-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='parcel',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='is_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='nature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parcels/photos/'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='parcelnotification',
            name='is_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcelnotification',
            name='offline_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelnotification',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
