# Generated by Django 5.1.6 on 2026-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
