# Generated by Django 5.1.6 on 2026-07-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedreport',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Grave')], max_length=10, null=True),
        ),
    ]
