# Generated by Django 5.1.6 on 2026-07-01 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_documents_and_more'),
        ('subscriptions', '0002_subscriptioninvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_agents',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_vehicles',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
