# Generated by Django 5.1.6 on 2026-07-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('otp_required', 'Code de confirmation attendu'), ('paid', 'Paye'), ('failed', 'Echoue'), ('refunded', 'Rembourse')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('is_used', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Code de confirmation de paiement',
                'verbose_name_plural': 'Codes de confirmation de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_d075fc_idx')],
            },
        ),
    ]
