# Generated by Django 5.1.6 on 2026-08-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_provider_ref_alter_payment_status_paymentotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('fingerprint', models.CharField(max_length=64)),
                ('body', models.BinaryField()),
                ('signature_valid', models.BooleanField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Notification de paiement',
                'verbose_name_plural': 'Notifications de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', '-created_at'], name='payments_pa_provide_6dad55_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'fingerprint'), name='paiement_notification_unique_par_corps')],
            },
        ),
    ]
