# Generated by Django 5.1.6 on 2026-06-29 22:01

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, unique=True, validators=[utils.validators.validate_phone_bf]),
        ),
    ]
