# Generated by Django 5.1.6 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_departure_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_parcel_arrival',
            field=models.BooleanField(default=True),
        ),
    ]
