# Generated by Django 5.1.6 on 2026-06-30 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('companies', '0003_company_parcel_pricing_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_type', models.CharField(choices=[('retard', 'Retard'), ('perte_bagage', 'Perte de bagage'), ('bagage_endommage', 'Bagage endommage'), ('comportement', 'Comportement'), ('surcharge', 'Surcharge'), ('remboursement', 'Remboursement'), ('autre', 'Autre')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('in_progress', 'En traitement'), ('resolved', 'Resolue'), ('closed', 'Cloturee'), ('escalated', 'Escaladee')], default='submitted', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='bookings.booking')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='companies.company')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamation',
                'verbose_name_plural': 'Reclamations',
                'ordering': ['-created_at'],
            },
        ),
    ]
