# Generated by Django 5.1.6 on 2026-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='claims/attachments/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
