# Generated by Django 5.1.6 on 2026-07-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_attachment_claim_ticket_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='attachment',
        ),
        migrations.CreateModel(
            name='ClaimAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='claims/attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Piece jointe de reclamation',
                'verbose_name_plural': 'Pieces jointes de reclamation',
                'ordering': ['id'],
            },
        ),
    ]
