# Generated by Django 5.1.6 on 2026-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_remove_claim_attachment_claimattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='traveler_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
