# Generated by Django 5.1.6 on 2026-06-30 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookings_synced', models.PositiveIntegerField(default=0)),
                ('parcels_synced', models.PositiveIntegerField(default=0)),
                ('validations_synced', models.PositiveIntegerField(default=0)),
                ('conflicts_count', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de synchronisation',
                'verbose_name_plural': 'Journaux de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(choices=[('booking', 'Reservation'), ('parcel', 'Colis'), ('validation', 'Embarquement')], default='booking', max_length=20)),
                ('conflict_type', models.CharField(choices=[('seat_conflict', 'Conflit de siege'), ('trip_full', 'Voyage complet'), ('trip_unavailable', 'Voyage indisponible'), ('duplicate', 'Doublon ignore'), ('invalid', 'Donnee invalide')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=30)),
                ('original_seat', models.CharField(blank=True, max_length=10)),
                ('assigned_seat', models.CharField(blank=True, max_length=10)),
                ('resolution', models.TextField()),
                ('resolved', models.BooleanField(default=True)),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.synclog')),
            ],
            options={
                'verbose_name': 'Conflit de synchronisation',
                'verbose_name_plural': 'Conflits de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
    ]
