# Generated by Django 5.1.6 on 2026-07-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='error_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('success', 'Succes'), ('partial', 'Partiel'), ('error', 'Erreur')], default='success', max_length=20),
        ),
    ]
