# Generated by Django 5.1.6 on 2026-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_synclog_error_details_synclog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='parcel_notifications_synced',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
