# Generated by Django 5.1.6 on 2026-08-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_synclog_parcel_notifications_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='cancellations_synced',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
