# Generated by Django 5.1.6 on 2026-07-01 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('geography', '0002_city_station_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_dropoff', to='geography.city'),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_luggage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='id_type',
            field=models.CharField(blank=True, choices=[('CNIB', 'CNIB'), ('passeport', 'Passeport')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='luggage_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_boarding', to='geography.city'),
        ),
    ]
