# Generated by Django 5.1.6 on 2026-07-21 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_destination_city_booking_discount_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(max_length=20)),
                ('result', models.CharField(choices=[('valid', 'Billet valide'), ('unpaid', 'Paiement non confirme'), ('cancelled', 'Reservation annulee'), ('refunded', 'Reservation remboursee'), ('already_boarded', 'Passager deja embarque'), ('invalid', 'Billet invalide'), ('not_found', 'Billet introuvable')], max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Scan de billet',
                'verbose_name_plural': 'Scans de billet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='bookings_sc_agent_i_c8ce71_idx')],
            },
        ),
    ]
