# Generated by Django 5.1.6 on 2026-07-23 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_print_count_booking_printed_at_scanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=30, unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('location', models.CharField(choices=[('hold', 'En soute'), ('cabin', 'En cabine')], default='hold', max_length=10)),
                ('is_offline', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baggage', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Bagage',
                'verbose_name_plural': 'Bagages',
                'ordering': ['id'],
            },
        ),
    ]
