# Generated by Django 5.1.6 on 2026-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_baggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id_type',
            field=models.CharField(blank=True, choices=[('none', 'Aucune'), ('cnib', 'CNIB'), ('passport', 'Passeport')], default='none', max_length=20),
        ),
    ]
