# Generated by Django 5.1.6 on 2026-07-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_testimonial',
            field=models.BooleanField(default=False),
        ),
    ]
